// Dicionário de Traduções
const i18n = {
    'pt': { 
        'str_all': '6 cordas', 'lbl_strings': 'Cordas', 'lbl_auto': 'auto', 'starting_in': 'Iniciando em', 'roots': ['C-dó', 'C#-dó#', 'D-ré', 'D#-ré#', 'E-mi', 'F-fá', 'F#-fá#', 'G-sol', 'G#-sol#', 'A-lá', 'A#-lá#', 'B-si'], 'skin_light': '☀️ Claro', 'skin_dark': '🌙 Escuro', 'skin_vintage': '🎸 Vintage', 'title': 'Tutor de Escalas', 'lbl_root': 'Tom', 'lbl_scale': 'Escala', 'lbl_mode': 'Variação', 'lbl_ex': 'Exercício', 'lbl_bpm': 'Velocidade', 'lbl_challenge': 'Desafio', 'btn_play_full': 'Tocar Escala Completa', 'btn_play': 'Tocar', 'btn_stop': 'Parar', 'position': 'Posição', 'frets': 'Trastes', 'ex_1': '1. Subir e descer a escala toda', 'ex_2': '2. 2 vezes cada nota', 'ex_3': '3. 3 vezes cada nota', 'ex_4': '4. Grupos de 3 (1-2-3, 2-3-4...)', 'ex_5': '5. Grupos de 4 (1-2-3-4, 2-3-4-5...)', 'ex_6': '6. Saltos de Terças (1-3, 2-4, 3-5...)', 'ex_7': '7. Arpejos Tríades', 'ex_8': '8. Arpejos Tétrades', 'ex_9': '9. Salto de Cordas (6-4, 5-3, 4-2...)', 'Pentatônica': 'Pentatônica', 'Maior': 'Maior', 'Menor': 'Menor', 'Modos Gregos': 'Modos Gregos', 'Jônio (Maior)': 'Jônio (Maior)', 'Dórico': 'Dórico', 'Frígio': 'Frígio', 'Lídio': 'Lídio', 'Mixolídio': 'Mixolídio', 'Eólio (Menor)': 'Eólio (Menor)', 'Lócrio': 'Lócrio', 'Escala Blues': 'Escala Blues', 'Menor Harmônica': 'Menor Harmônica', 'Padrão': 'Padrão', 'Menor Melódica': 'Menor Melódica', 'Escalas Simétricas': 'Escalas Simétricas', 'Diminuta (Tom-Semitom)': 'Diminuta (Tom-Semitom)', 'Dom Diminuta (Semitom-Tom)': 'Dom Diminuta (Semitom-Tom)', 'Hexafônica (Tons Inteiros)': 'Hexafônica (Tons Inteiros)',
        'help_title': 'Ajuda & Funcionalidades',
        'help_level_notice': '⚠️ Este software é recomendado para estudantes de nível intermediário na guitarra ou violão.',
        'help_how_to_start_title': 'Como Iniciar?',
        'help_how_to_start_text': 'Afine o seu instrumento na afinação padrão (EADGBE). Clique no botão "Tocar" da primeira posição e acompanhe as notas piscando na tela. Aumente a velocidade ou avance para a próxima posição quando se sentir confiante!',
        'help_intro': 'Entenda os controles:',
        'help_root': 'Define a nota fundamental (raiz) do exercício.',
        'help_scale': 'Escolhe a família da escala (Pentatônica, Diatônica, etc).',
        'help_mode': 'Altera o modo ou variação dentro da família selecionada.',
        'help_ex': 'Muda o padrão de movimento sonoro (subir/descer, saltos, arpejos).',
        'help_strings': 'Isole a prática em grupos específicos de cordas no braço.',
        'help_speed': 'Ajusta as batidas por minuto. O modo "auto" aumenta 10 BPM a cada X repetições.',
        'help_challenge': 'Invisibiliza os marcadores progressivamente para treinar a sua memória visual!',
        'help_lbl_pos': 'Posições 1-5',
        'help_positions': 'Representam os formatos do sistema CAGED, fatiando a escala em blocos fáceis de memorizar.',
        'help_lbl_full': 'Escala Completa',
        'help_full_scale': 'Exibe todo o braço do instrumento, dando uma visão panorâmica de como as posições se conectam.',
        'bt_modal_title': 'Ideia de Harmonia',
        'bt_modal_text': 'Grave ou procure por uma Backing Track (Trilha de Fundo) com os seguintes acordes para improvisar perfeitamente em cima desta escala:',
        'bt_style': 'Estilo:',
        'bt_desc_1': 'Progressão Pop/Rock Clássica',
        'bt_desc_2': 'Vamp Groove Dórico',
        'bt_desc_3': 'Vamp Frígio / Metal',
        'bt_desc_4': 'Vamp Lídio / Sonhador',
        'bt_desc_5': 'Clássico Rock do Sul',
        'bt_desc_6': 'Rock Menor Épico',
        'bt_desc_7': 'Tensão Sombria',
        'bt_desc_8': 'Blues Texas / Country',
        'bt_desc_9': 'Blues Menor Tradicional',
        'bt_desc_10': 'Tensão Neoclássica / Flamenco',
        'bt_desc_11': 'Jazz Menor / Fusion',
        'bt_desc_12': 'Tensão Contínua (Acorde Diminuto Estático)',
        'bt_desc_13': 'Atmosfera Hexafônica (Acorde Aumentado Estático)',
        'bt_desc_14': 'Vamp Estático / Drone',
        'lbl_backing_track': 'Backing Track',
        'lbl_harmonic_field': 'Campo Harmônico',
        'lbl_degree': 'Grau',
        'hf_not_applicable': 'Campo harmônico diatônico não aplicável para esta escala.'
    },
    'de': { 
        'str_all': '6 Saiten', 'lbl_auto': 'auto', 'starting_in': 'Startet in', 'roots': ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'], 'skin_light': '☀️ Hell', 'skin_dark': '🌙 Dunkel', 'skin_vintage': '🎸 Vintage', 'title': 'Tonleiter-Tutor', 'lbl_root': 'Grundton', 'lbl_scale': 'Tonleiter', 'lbl_mode': 'Variation', 'lbl_ex': 'Übung', 'lbl_bpm': 'Tempo', 'lbl_challenge': 'Herausforderung', 'btn_play_full': 'Ganze Tonleiter spielen', 'btn_play': 'Spielen', 'btn_stop': 'Stopp', 'position': 'Position', 'frets': 'Bünde', 'ex_1': '1. Ganze Tonleiter hoch und runter', 'ex_2': '2. Jede Note 2 mal', 'ex_3': '3. Jede Note 3 mal', 'ex_4': '4. 3er-Gruppen (1-2-3, 2-3-4...)', 'ex_5': '5. 4er-Gruppen (1-2-3-4, 2-3-4-5...)', 'ex_6': '6. Terzsprünge (1-3, 2-4, 3-5...)', 'ex_7': '7. Dreiklang-Arpeggios', 'ex_8': '8. Vierklang-Arpeggios', 'ex_9': '9. Saitensprünge (6-4, 5-3, 4-2...)', 'Pentatônica': 'Pentatonik', 'Maior': 'Dur', 'Menor': 'Moll', 'Modos Gregos': 'Kirchentonarten', 'Jônio (Maior)': 'Ionisch (Dur)', 'Dórico': 'Dorisch', 'Frígio': 'Phrygisch', 'Lídio': 'Lydisch', 'Mixolídio': 'Mixolydisch', 'Eólio (Menor)': 'Äolisch (Moll)', 'Lócrio': 'Lokrisch', 'Escala Blues': 'Blues-Tonleiter', 'Menor Harmônica': 'Harmonisch Moll', 'Padrão': 'Standard', 'Menor Melódica': 'Melodisch Moll', 'Escalas Simétricas': 'Symmetrische Tonleitern', 'Diminuta (Tom-Semitom)': 'Vermindert (G-H)', 'Dom Diminuta (Semitom-Tom)': 'Dom. Vermindert (H-G)', 'Hexafônica (Tons Inteiros)': 'Ganztonleiter',
        'help_title': 'Hilfe & Funktionen',
        'help_level_notice': '⚠️ Diese Software wird für fortgeschrittene Gitarristen empfohlen.',
        'help_how_to_start_title': 'Wie fange ich an?',
        'help_how_to_start_text': 'Stimmen Sie Ihr Instrument auf die Standardstimmung (EADGBE). Klicken Sie auf die Schaltfläche "Spielen" der ersten Position und folgen Sie den blinkenden Noten auf dem Bildschirm. Erhöhen Sie das Tempo oder wechseln Sie zur nächsten Position, wenn Sie sich sicher fühlen!',
        'help_intro': 'Verstehen Sie die Steuerung:',
        'help_root': 'Definiert den Grundton der Übung.',
        'help_scale': 'Wählt die Tonleiterfamilie (Pentatonik, Diatonik usw.).',
        'help_mode': 'Ändert den Modus oder die Variation innerhalb der ausgewählten Familie.',
        'help_ex': 'Ändert das Zupf-/Bewegungsmuster (rauf/runter, Sprünge, Arpeggios).',
        'help_strings': 'Isoliert die Übung auf bestimmte Saitengruppen auf dem Griffbrett.',
        'help_speed': 'Passt die Schläge pro Minute an. Der "auto"-Modus erhöht alle X Wiederholungen um 10 BPM.',
        'help_challenge': 'Versteckt die Markierungen schrittweise, um Ihr visuelles Gedächtnis zu trainieren!',
        'help_lbl_pos': 'Positionen 1-5',
        'help_positions': 'Repräsentieren die Formen des CAGED-Systems und unterteilen die Tonleiter in leicht zu merkende Blöcke.',
        'help_lbl_full': 'Ganze Tonleiter',
        'help_full_scale': 'Zeigt das gesamte Griffbrett an und gibt einen Überblick, wie die Positionen verbunden sind.',
        'bt_modal_title': 'Harmonie-Idee',
        'bt_modal_text': 'Nimm einen Backing Track mit folgenden Akkorden auf oder suche danach, um perfekt über diese Tonleiter zu improvisieren:',
        'bt_style': 'Stil:',
        'bt_desc_1': 'Klassische Pop/Rock-Akkordfolge',
        'bt_desc_2': 'Dorischer Groove Vamp',
        'bt_desc_3': 'Phrygischer / Metal Vamp',
        'bt_desc_4': 'Lydischer / Verträumter Vamp',
        'bt_desc_5': 'Southern Rock Klassiker',
        'bt_desc_6': 'Epischer Moll-Rock',
        'bt_desc_7': 'Dunkle Spannung',
        'bt_desc_8': 'Texas / Country Blues',
        'bt_desc_9': 'Traditioneller Moll-Blues',
        'bt_desc_10': 'Neoklassische Spannung / Flamenco',
        'bt_desc_11': 'Moll-Jazz / Fusion',
        'bt_desc_12': 'Dauerspannung (Verminderter Akkord)',
        'bt_desc_13': 'Ganzton-Atmosphäre (Übermäßiger Akkord)',
        'bt_desc_14': 'Statischer Vamp / Drone',
        'lbl_backing_track': 'Backing Track',
        'lbl_harmonic_field': 'Harmonisches Feld',
        'lbl_degree': 'Stufe',
        'hf_not_applicable': 'Harmonisches Feld nicht anwendbar (nicht-diatonische Tonleiter).'
    },
    'en': { 
        'str_all': '6 strings', 'lbl_strings': 'Strings', 'lbl_auto': 'auto', 'starting_in': 'Starting in', 'roots': ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'], 'skin_light': '☀️ Light', 'skin_dark': '🌙 Dark', 'skin_vintage': '🎸 Vintage', 'title': 'Scale Tutor', 'lbl_root': 'Root', 'lbl_scale': 'Scale', 'lbl_mode': 'Variation', 'lbl_ex': 'Exercise', 'lbl_bpm': 'Speed', 'lbl_challenge': 'Challenge', 'btn_play_full': 'Play Full Scale', 'btn_play': 'Play', 'btn_stop': 'Stop', 'position': 'Position', 'frets': 'Frets', 'ex_1': '1. Up and down the whole scale', 'ex_2': '2. 2 times each note', 'ex_3': '3. 3 times each note', 'ex_4': '4. Groups of 3 (1-2-3, 2-3-4...)', 'ex_5': '5. Groups of 4 (1-2-3-4, 2-3-4-5...)', 'ex_6': '6. Third leaps (1-3, 2-4, 3-5...)', 'ex_7': '7. Triad Arpeggios', 'ex_8': '8. Tetrad Arpeggios', 'ex_9': '9. String skipping (6-4, 5-3, 4-2...)', 'Pentatônica': 'Pentatonic', 'Maior': 'Major', 'Menor': 'Minor', 'Modos Gregos': 'Greek Modes', 'Jônio (Maior)': 'Ionian (Major)', 'Dórico': 'Dorian', 'Frígio': 'Phrygian', 'Lídio': 'Lydian', 'Mixolídio': 'Mixolydian', 'Eólio (Menor)': 'Aeolian (Minor)', 'Lócrio': 'Locrian', 'Escala Blues': 'Blues Scale', 'Menor Harmônica': 'Harmonic Minor', 'Padrão': 'Standard', 'Menor Melódica': 'Melodic Minor', 'Escalas Simétricas': 'Symmetrical Scales', 'Diminuta (Tom-Semitom)': 'Diminished (W-H)', 'Dom Diminuta (Semitom-Tom)': 'Dom Diminished (H-W)', 'Hexafônica (Tons Inteiros)': 'Whole Tone',
        'help_title': 'Help & Features',
        'help_level_notice': '⚠️ This software is recommended for intermediate guitar or acoustic guitar players.',
        'help_how_to_start_title': 'How to Start?',
        'help_how_to_start_text': 'Tune your instrument to standard tuning (EADGBE). Click the "Play" button on the first position and follow the flashing notes on the screen. Increase the speed or move to the next position when you feel confident!',
        'help_intro': 'Understand the controls:',
        'help_root': 'Defines the fundamental (root) note of the exercise.',
        'help_scale': 'Chooses the scale family (Pentatonic, Diatonic, etc).',
        'help_mode': 'Changes the mode or variation within the selected family.',
        'help_ex': 'Changes the picking/movement pattern (up/down, leaps, arpeggios).',
        'help_strings': 'Isolates practice to specific string groups on the fretboard.',
        'help_speed': 'Adjusts beats per minute. The "auto" mode increases 10 BPM every X repetitions.',
        'help_challenge': 'Progressively hides the markers to train your visual memory!',
        'help_lbl_pos': 'Positions 1-5',
        'help_positions': 'Represent the CAGED system shapes, slicing the scale into easy-to-memorize blocks.',
        'help_lbl_full': 'Full Scale',
        'help_full_scale': 'Displays the entire fretboard, giving a panoramic view of how the positions connect.',
        'bt_modal_title': 'Harmony Idea',
        'bt_modal_text': 'Record or search for a Backing Track with the following chords to improvise perfectly over this scale:',
        'bt_style': 'Style:',
        'bt_desc_1': 'Classic Pop/Rock Progression',
        'bt_desc_2': 'Dorian Groove Vamp',
        'bt_desc_3': 'Phrygian / Metal Vamp',
        'bt_desc_4': 'Lydian / Dreamy Vamp',
        'bt_desc_5': 'Southern Rock Classic',
        'bt_desc_6': 'Epic Minor Rock',
        'bt_desc_7': 'Dark Tension',
        'bt_desc_8': 'Texas / Country Blues',
        'bt_desc_9': 'Traditional Minor Blues',
        'bt_desc_10': 'Neoclassical Tension / Flamenco',
        'bt_desc_11': 'Minor Jazz / Fusion',
        'bt_desc_12': 'Continuous Tension (Diminished Chord)',
        'bt_desc_13': 'Whole Tone Atmosphere (Augmented Chord)',
        'bt_desc_14': 'Static Vamp / Drone',
        'lbl_backing_track': 'Backing Track',
        'lbl_harmonic_field': 'Harmonic Field',
        'lbl_degree': 'Degree',
        'hf_not_applicable': 'Harmonic field not applicable (non-diatonic scale).'
    },
    'es': { 
        'str_all': '6 cuerdas', 'lbl_strings': 'Cuerdas', 'lbl_auto': 'auto', 'starting_in': 'Iniciando en', 'roots': ['C-do', 'C#-do#', 'D-re', 'D#-re#', 'E-mi', 'F-fa', 'F#-fa#', 'G-sol', 'G#-sol#', 'A-la', 'A#-la#', 'B-si'], 'skin_light': '☀️ Claro', 'skin_dark': '🌙 Oscuro', 'skin_vintage': '🎸 Vintage', 'title': 'Tutor de Escalas', 'lbl_root': 'Tono', 'lbl_scale': 'Escala', 'lbl_mode': 'Variación', 'lbl_ex': 'Ejercicio', 'lbl_bpm': 'Velocidad', 'lbl_challenge': 'Desafío', 'btn_play_full': 'Tocar Escala Completa', 'btn_play': 'Tocar', 'btn_stop': 'Detener', 'position': 'Posición', 'frets': 'Trastes', 'ex_1': '1. Subir y bajar toda la escala', 'ex_2': '2. 2 veces cada nota', 'ex_3': '3. 3 veces cada nota', 'ex_4': '4. Grupos de 3 (1-2-3, 2-3-4...)', 'ex_5': '5. Grupos de 4 (1-2-3-4, 2-3-4-5...)', 'ex_6': '6. Saltos de Terceras (1-3, 2-4, 3-5...)', 'ex_7': '7. Arpegios Tríadas', 'ex_8': '8. Arpegios Tétradas', 'ex_9': '9. Salto de Cuerdas (6-4, 5-3, 4-2...)', 'Pentatônica': 'Pentatónica', 'Maior': 'Mayor', 'Menor': 'Menor', 'Modos Gregos': 'Modos Griegos', 'Jônio (Maior)': 'Jónico (Mayor)', 'Dórico': 'Dórico', 'Frígio': 'Frigio', 'Lídio': 'Lidio', 'Mixolídio': 'Mixolidio', 'Eólio (Menor)': 'Eólico (Menor)', 'Lócrio': 'Locrio', 'Escala Blues': 'Escala Blues', 'Menor Harmônica': 'Menor Armónica', 'Padrão': 'Estándar', 'Menor Melódica': 'Menor Melódica', 'Escalas Simétricas': 'Escalas Simétricas', 'Diminuta (Tom-Semitom)': 'Disminuida (T-S)', 'Dom Diminuta (Semitom-Tom)': 'Dom Disminuida (S-T)', 'Hexafônica (Tons Inteiros)': 'Hexáfona (Tonos Enteros)',
        'help_title': 'Ayuda y Funciones',
        'help_level_notice': '⚠️ Este software está recomendado para estudiantes de nivel intermedio en guitarra acústica o eléctrica.',
        'help_how_to_start_title': '¿Cómo Empezar?',
        'help_how_to_start_text': 'Afina tu instrumento en afinación estándar (EADGBE). Haz clic en el botón "Tocar" de la primera posición y sigue las notas que parpadean en la pantalla. ¡Aumenta la velocidad o avanza a la siguiente posición cuando te sientas seguro!',
        'help_intro': 'Entiende los controles:',
        'help_root': 'Define la nota fundamental (raíz) del ejercicio.',
        'help_scale': 'Elige la familia de la escala (Pentatónica, Diatónica, etc).',
        'help_mode': 'Cambia el modo o variación dentro de la familia seleccionada.',
        'help_ex': 'Cambia el patrón de movimiento (subir/bajar, saltos, arpegios).',
        'help_strings': 'Aísla la práctica en grupos específicos de cuerdas.',
        'help_speed': 'Ajusta las pulsaciones por minuto. El modo "auto" aumenta 10 BPM cada X repeticiones.',
        'help_challenge': '¡Oculta los marcadores progresivamente para poner a prueba tu memoria visual!',
        'help_lbl_pos': 'Posiciones 1-5',
        'help_positions': 'Representan los patrones del sistema CAGED, dividiendo la escala en bloques fáciles de memorizar.',
        'help_lbl_full': 'Escala Completa',
        'help_full_scale': 'Muestra todo el mástil, dando una visión panorámica de cómo se conectan las posiciones.',
        'bt_modal_title': 'Idea de Armonía',
        'bt_modal_text': 'Graba o busca una Backing Track (Pista de Acompañamiento) con los siguientes acordes para improvisar perfectamente sobre esta escala:',
        'bt_style': 'Estilo:',
        'bt_desc_1': 'Progresión Pop/Rock Clásica',
        'bt_desc_2': 'Vamp Groove Dórico',
        'bt_desc_3': 'Vamp Frigio / Metal',
        'bt_desc_4': 'Vamp Lidio / Soñador',
        'bt_desc_5': 'Clásico Rock Sureño',
        'bt_desc_6': 'Rock Menor Épico',
        'bt_desc_7': 'Tensión Oscura',
        'bt_desc_8': 'Blues Texas / Country',
        'bt_desc_9': 'Blues Menor Tradicional',
        'bt_desc_10': 'Tensión Neoclásica / Flamenco',
        'bt_desc_11': 'Jazz Menor / Fusión',
        'bt_desc_12': 'Tensión Continua (Acorde Disminuido)',
        'bt_desc_13': 'Atmósfera Hexáfona (Acorde Aumentado)',
        'bt_desc_14': 'Vamp Estático / Drone',
        'lbl_backing_track': 'Backing Track',
        'lbl_harmonic_field': 'Campo Armónico',
        'lbl_degree': 'Grado',
        'hf_not_applicable': 'Campo armónico no aplicable (escala no diatónica).'
    },
    'fr': { 
        'str_all': '6 cordes', 'lbl_auto': 'auto', 'starting_in': 'Démarrage dans', 'roots': ['C-do', 'C#-do#', 'D-ré', 'D#-ré#', 'E-mi', 'F-fa', 'F#-fa#', 'G-sol', 'G#-sol#', 'A-la', 'A#-la#', 'B-si'], 'skin_light': '☀️ Clair', 'skin_dark': '🌙 Sombre', 'skin_vintage': '🎸 Vintage', 'title': 'Tuteur de Gammes', 'lbl_root': 'Tonalité', 'lbl_scale': 'Gamme', 'lbl_mode': 'Variation', 'lbl_ex': 'Exercice', 'lbl_bpm': 'Vitesse', 'lbl_challenge': 'Défi', 'btn_play_full': 'Jouer la Gamme Complète', 'btn_play': 'Jouer', 'btn_stop': 'Arrêter', 'position': 'Position', 'frets': 'Frettes', 'ex_1': '1. Monter et descendre toute la gamme', 'ex_2': '2. 2 fois chaque note', 'ex_3': '3. 3 fois chaque note', 'ex_4': '4. Groupes de 3 (1-2-3, 2-3-4...)', 'ex_5': '5. Groupes de 4 (1-2-3-4, 2-3-4-5...)', 'ex_6': '6. Sauts de Tierces (1-3, 2-4, 3-5...)', 'ex_7': '7. Arpèges Triades', 'ex_8': '8. Arpèges Tétrades', 'ex_9': '9. Saut de Cordes (6-4, 5-3...)', 'Pentatônica': 'Pentatonique', 'Maior': 'Majeure', 'Menor': 'Mineure', 'Modos Gregos': 'Modes Grecs', 'Jônio (Maior)': 'Ionien (Majeur)', 'Dórico': 'Dorien', 'Frígio': 'Phrygien', 'Lídio': 'Lydien', 'Mixolídio': 'Mixolydien', 'Eólio (Menor)': 'Éolien (Mineur)', 'Lócrio': 'Locrien', 'Escala Blues': 'Gamme Blues', 'Menor Harmônica': 'Mineure Harmonique', 'Padrão': 'Standard', 'Menor Melódica': 'Mineure Mélodique', 'Escalas Simétricas': 'Gammes Symétriques', 'Diminuta (Tom-Semitom)': 'Diminuée (Ton-Demi-ton)', 'Dom Diminuta (Semitom-Tom)': 'Dom Diminuée (Demi-ton-Ton)', 'Hexafônica (Tons Inteiros)': 'Par Tons (Hexatonique)',
        'help_title': 'Aide & Fonctionnalités',
        'help_level_notice': '⚠️ Ce logiciel est recommandé pour les étudiants de niveau intermédiaire.',
        'help_how_to_start_title': 'Comment commencer ?',
        'help_how_to_start_text': 'Accordez votre instrument en accordage standard (EADGBE). Cliquez sur le bouton "Jouer" de la première position et suivez les notes clignotantes. Augmentez la vitesse ou passez à la position suivante lorsque vous vous sentez confiant !',
        'help_intro': 'Comprendre les contrôles :',
        'help_root': 'Définit la note fondamentale (racine) de l\'exercice.',
        'help_scale': 'Choisit la famille de gammes (Pentatonique, Diatonique, etc.).',
        'help_mode': 'Modifie le mode ou la variation dans la famille sélectionnée.',
        'help_ex': 'Modifie le motif de mouvement sonore (monter/descendre, sauts, arpèges).',
        'help_strings': 'Isolez la pratique sur des groupes de cordes spécifiques.',
        'help_speed': 'Ajuste les battements par minute. Le mode "auto" augmente de 10 BPM toutes les X répétitions.',
        'help_challenge': 'Masque progressivement les marqueurs pour entraîner votre mémoire visuelle !',
        'help_lbl_pos': 'Positions 1-5',
        'help_positions': 'Représentent les formes du système CAGED, découpant la gamme en blocs faciles à mémoriser.',
        'help_lbl_full': 'Gamme Complète',
        'help_full_scale': 'Affiche tout le manche de l\'instrument, donnant une vue panoramique de la façon dont les positions se connectent.',
        'bt_modal_title': 'Idée d\'Harmonie',
        'bt_modal_text': 'Enregistrez ou recherchez un Backing Track avec les accords suivants pour improviser parfaitement sur cette gamme :',
        'bt_style': 'Style :',
        'bt_desc_1': 'Progression Pop/Rock Classique',
        'bt_desc_2': 'Vamp Groove Dorien',
        'bt_desc_3': 'Vamp Phrygien / Metal',
        'bt_desc_4': 'Vamp Lydien / Rêveur',
        'bt_desc_5': 'Classique Rock Sudiste',
        'bt_desc_6': 'Rock Mineur Épique',
        'bt_desc_7': 'Tension Sombre',
        'bt_desc_8': 'Blues Texas / Country',
        'bt_desc_9': 'Blues Mineur Traditionnel',
        'bt_desc_10': 'Tension Néoclassique / Flamenco',
        'bt_desc_11': 'Jazz Mineur / Fusion',
        'bt_desc_12': 'Tension Continue (Accord Diminué)',
        'bt_desc_13': 'Atmosphère Hexatonique (Accord Augmenté)',
        'bt_desc_14': 'Vamp Statique / Drone',
        'lbl_backing_track': 'Backing Track',
        'lbl_harmonic_field': 'Champ Harmonique',
        'lbl_degree': 'Degré',
        'hf_not_applicable': 'Champ harmonique non applicable (gamme non diatonique).'
    },
    'ru': { 
        'str_all': '6 струн', 'lbl_auto': 'auto', 'starting_in': 'Начало через', 'roots': ['C-до', 'C#-до#', 'D-ре', 'D#-ре#', 'E-ми', 'F-фа', 'F#-фа#', 'G-соль', 'G#-соль#', 'A-ля', 'A#-ля#', 'B-си'], 'skin_light': '☀️ Светлая', 'skin_dark': '🌙 Темная', 'skin_vintage': '🎸 Винтаж', 'title': 'Репетитор по Гаммам', 'lbl_root': 'Тоника', 'lbl_scale': 'Гамма', 'lbl_mode': 'Вариация', 'lbl_ex': 'Упражнение', 'lbl_bpm': 'Скорость', 'lbl_challenge': 'Вызов', 'btn_play_full': 'Играть Всю Гамму', 'btn_play': 'Играть', 'btn_stop': 'Стоп', 'position': 'Позиция', 'frets': 'Лады', 'ex_1': '1. Вверх и вниз по всей гамме', 'ex_2': '2. По 2 раза каждую ноту', 'ex_3': '3. По 3 раза каждую ноту', 'ex_4': '4. Группы по 3 (1-2-3, 2-3-4...)', 'ex_5': '5. Группы по 4 (1-2-3-4, 2-3-4-5...)', 'ex_6': '6. Скачки на терцию (1-3, 2-4, 3-5...)', 'ex_7': '7. Арпеджио Трезвучий', 'ex_8': '8. Арпеджио Септаккордов', 'ex_9': '9. Пропуск струн (6-4, 5-3, 4-2...)', 'Pentatônica': 'Пентатоника', 'Maior': 'Мажор', 'Menor': 'Минор', 'Modos Gregos': 'Лады', 'Jônio (Maior)': 'Ионийский', 'Dórico': 'Дорийский', 'Frígio': 'Фригийский', 'Lídio': 'Лидийский', 'Mixolídio': 'Миксолидийский', 'Eólio (Menor)': 'Эолийский', 'Lócrio': 'Локрийский', 'Escala Blues': 'Блюзовая Гамма', 'Menor Harmônica': 'Гармонический Минор', 'Padrão': 'Стандарт', 'Menor Melódica': 'Мелодический Минор', 'Escalas Simétricas': 'Симметричные Гаммы', 'Diminuta (Tom-Semitom)': 'Уменьшенная', 'Dom Diminuta (Semitom-Tom)': 'Дом. Уменьшенная', 'Hexafônica (Tons Inteiros)': 'Целотоновая',
        'help_title': 'Помощь и Функции',
        'help_level_notice': '⚠️ Это программное обеспечение рекомендуется для студентов среднего уровня.',
        'help_how_to_start_title': 'Как начать?',
        'help_how_to_start_text': 'Настройте ваш инструмент в стандартный строй (EADGBE). Нажмите кнопку «Играть» на первой позиции и следите за мигающими нотами на экране. Увеличьте скорость или перейдите к следующей позиции, когда почувствуете себя уверенно!',
        'help_intro': 'Поймите элементы управления:',
        'help_root': 'Определяет основную ноту (тонику) упражнения.',
        'help_scale': 'Выбирает семейство гамм (Пентатоника, Диатоника и т.д.).',
        'help_mode': 'Изменяет лад или вариацию внутри выбранного семейства.',
        'help_ex': 'Изменяет звуковой паттерн движения (вверх/вниз, скачки, арпеджио).',
        'help_strings': 'Изолируйте практику на конкретных группах струн на грифе.',
        'help_speed': 'Регулирует удары в минуту. Режим "auto" увеличивает темп на 10 BPM каждые X повторений.',
        'help_challenge': 'Постепенно скрывает маркеры, чтобы тренировать вашу зрительную память!',
        'help_lbl_pos': 'Позиции 1-5',
        'help_positions': 'Представляют форматы системы CAGED, разбивая гамму на легко запоминаемые блоки.',
        'help_lbl_full': 'Вся Гамма',
        'help_full_scale': 'Отображает весь гриф инструмента, давая панорамный вид того, как позиции соединяются.',
        'bt_modal_title': 'Идея Гармонии',
        'bt_modal_text': 'Запишите или найдите минусовку (Backing Track) со следующими аккордами, чтобы идеально импровизировать в этой гамме:',
        'bt_style': 'Стиль:',
        'bt_desc_1': 'Классическая Поп/Рок Прогрессия',
        'bt_desc_2': 'Дорийский Грув Вамп',
        'bt_desc_3': 'Фригийский / Метал Вамп',
        'bt_desc_4': 'Лидийский / Мечтательный Вамп',
        'bt_desc_5': 'Классика Южного Рока',
        'bt_desc_6': 'Эпический Минорный Рок',
        'bt_desc_7': 'Темное Напряжение',
        'bt_desc_8': 'Техасский / Кантри Блюз',
        'bt_desc_9': 'Традиционный Минорный Блюз',
        'bt_desc_10': 'Неоклассическое Напряжение / Фламенко',
        'bt_desc_11': 'Минорный Джаз / Фьюжн',
        'bt_desc_12': 'Постоянное Напряжение (Уменьшенный Аккорд)',
        'bt_desc_13': 'Целотоновая Атмосфера (Увеличенный Аккорд)',
        'bt_desc_14': 'Статический Вамп / Дрон',
        'lbl_backing_track': 'Backing Track',
        'lbl_harmonic_field': 'Гармоническое поле',
        'lbl_degree': 'Ступень',
        'hf_not_applicable': 'Гармоническое поле не применяется (недиатоническая гамма).'
    },
    'zh': { 
        'str_all': '6 弦', 'lbl_auto': 'auto', 'starting_in': '即将开始', 'roots': ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'], 'skin_light': '☀️ 浅色', 'skin_dark': '🌙 深色', 'skin_vintage': '🎸 复古', 'title': '音阶导师', 'lbl_root': '主音', 'lbl_scale': '音阶', 'lbl_mode': '变奏', 'lbl_ex': '练习', 'lbl_bpm': '速度', 'lbl_challenge': '挑战', 'btn_play_full': '弹奏全音阶', 'btn_play': '弹奏', 'btn_stop': '停止', 'position': '位置', 'frets': '品格', 'ex_1': '1. 上下全音阶', 'ex_2': '2. 每个音符弹2次', 'ex_3': '3. 每个音符弹3次', 'ex_4': '4. 三音组 (1-2-3, 2-3-4...)', 'ex_5': '5. 四音组 (1-2-3-4, 2-3-4-5...)', 'ex_6': '6. 三度跳跃 (1-3, 2-4, 3-5...)', 'ex_7': '7. 三和弦琶音', 'ex_8': '8. 七和弦琶音', 'ex_9': '9. 跳弦 (6-4, 5-3, 4-2...)', 'Pentatônica': '五声音阶', 'Maior': '大调', 'Menor': '小调', 'Modos Gregos': '调式', 'Jônio (Maior)': '伊奥尼亚', 'Dórico': '多利亚', 'Frígio': '弗里吉亚', 'Lídio': '利底亚', 'Mixolídio': '混合利底亚', 'Eólio (Menor)': '爱奥利亚', 'Lócrio': '洛克里亚', 'Escala Blues': '布鲁斯音阶', 'Menor Harmônica': '和声小调', 'Padrão': '标准', 'Menor Melódica': '旋律小调', 'Escalas Simétricas': '对称音阶', 'Diminuta (Tom-Semitom)': '减音阶', 'Dom Diminuta (Semitom-Tom)': '属减音阶', 'Hexafônica (Tons Inteiros)': '全音音阶',
        'help_title': '帮助与功能',
        'help_level_notice': '⚠️ 此软件推荐给中级水平的学生使用。',
        'help_how_to_start_title': '如何开始？',
        'help_how_to_start_text': '将您的乐器调至标准音高（EADGBE）。点击第一个位置的“弹奏”按钮，跟随屏幕上闪烁的音符。当您感到自信时，增加速度或进入下一个位置！',
        'help_intro': '了解控件：',
        'help_root': '定义练习的根音。',
        'help_scale': '选择音阶家族（五声、自然等）。',
        'help_mode': '更改所选家族中的调式或变奏。',
        'help_ex': '更改声音移动模式（上下、跳跃、琶音）。',
        'help_strings': '在指板上分离特定弦组进行练习。',
        'help_speed': '调整每分钟节拍。 “auto”模式每X次重复增加10 BPM。',
        'help_challenge': '逐渐隐藏标记以训练您的视觉记忆！',
        'help_lbl_pos': '位置 1-5',
        'help_positions': '代表 CAGED 系统的格式，将音阶切成易于记忆的块。',
        'help_lbl_full': '完整音阶',
        'help_full_scale': '显示乐器的整个指板，提供位置如何连接的全景视图。',
        'bt_modal_title': '和声灵感',
        'bt_modal_text': '录制或搜索包含以下和弦的伴奏音轨（Backing Track），以便在此音阶上完美即兴：',
        'bt_style': '风格：',
        'bt_desc_1': '经典流行/摇滚进行',
        'bt_desc_2': '多利亚律动反复',
        'bt_desc_3': '弗里吉亚 / 金属反复',
        'bt_desc_4': '利底亚 / 梦幻反复',
        'bt_desc_5': '南方摇滚经典',
        'bt_desc_6': '史诗小调摇滚',
        'bt_desc_7': '黑暗张力',
        'bt_desc_8': '德州 / 乡村布鲁斯',
        'bt_desc_9': '传统小调布鲁斯',
        'bt_desc_10': '新古典张力 / 弗拉门戈',
        'bt_desc_11': '小调爵士 / 融合',
        'bt_desc_12': '持续张力（减和弦）',
        'bt_desc_13': '全音阶氛围（增和弦）',
        'bt_desc_14': '静态反复 / 持续音',
        'lbl_backing_track': 'Backing Track',
        'lbl_harmonic_field': '和声场',
        'lbl_degree': '级',
        'hf_not_applicable': '和声场不适用（非自然音阶）。'
    },
    'hi': { 
        'str_all': '6 तार', 'lbl_auto': 'auto', 'starting_in': 'में शुरू हो रहा है', 'roots': ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'], 'skin_light': '☀️ हल्का', 'skin_dark': '🌙 गहरा', 'skin_vintage': '🎸 विंटेज', 'title': 'स्केल ट्यूटर', 'lbl_root': 'मूल स्वर', 'lbl_scale': 'स्केल', 'lbl_mode': 'रूपांतर', 'lbl_ex': 'व्यायाम', 'lbl_bpm': 'गति', 'lbl_challenge': 'चुनौती', 'btn_play_full': 'पूरा स्केल बजाएं', 'btn_play': 'बजाएं', 'btn_stop': 'रुकें', 'position': 'स्थिति', 'frets': 'फ्रेट्स', 'ex_1': '1. पूरा स्केल ऊपर-नीचे', 'ex_2': '2. 2 बार प्रत्येक स्वर', 'ex_3': '3. 3 बार प्रत्येक स्वर', 'ex_4': '4. 3 के समूह (1-2-3, 2-3-4...)', 'ex_5': '5. 4 के समूह (1-2-3-4, 2-3-4-5...)', 'ex_6': '6. थर्ड्स जंप (1-3, 2-4, 3-5...)', 'ex_7': '7. ट्रायड आर्पेजियोस', 'ex_8': '8. टेट्राड आर्पेजियोस', 'ex_9': '9. स्ट्रिंग जंपिंग (6-4, 5-3, 4-2...)', 'Pentatônica': 'पेंटाटोनिक', 'Maior': 'मेजर', 'Menor': 'माइनर', 'Modos Gregos': 'मोड्स', 'Jônio (Maior)': 'आयोनियन', 'Dórico': 'डोरियन', 'Frígio': 'फ्रिजियन', 'Lídio': 'लिडियान', 'Mixolídio': 'मिक्सोलिडियन', 'Eólio (Menor)': 'एओलियन', 'Lócrio': 'लोक्रियन', 'Escala Blues': 'ब्लूज़ स्केल', 'Menor Harmônica': 'हार्मोनिक माइनर', 'Padrão': 'मानक', 'Menor Melódica': 'मेलोडिक माइनर', 'Escalas Simétricas': 'सिमेट्रिकल स्केल', 'Diminuta (Tom-Semitom)': 'डिमिनिश्ड', 'Dom Diminuta (Semitom-Tom)': 'डोम डिमिनिश्ड', 'Hexafônica (Tons Inteiros)': 'होल टोन',
        'help_title': 'सहायता और विशेषताएं',
        'help_level_notice': '⚠️ यह सॉफ़्टवेयर इंटरमीडिएट स्तर के छात्रों के लिए अनुशंसित है।',
        'help_how_to_start_title': 'शुरुआत कैसे करें?',
        'help_how_to_start_text': 'अपने वाद्ययंत्र को मानक ट्यूनिंग (EADGBE) में ट्यून करें। पहली स्थिति पर "बजाएं" बटन पर क्लिक करें और स्क्रीन पर चमकते हुए नोटों का पालन करें। जब आप आश्वस्त महसूस करें तो गति बढ़ाएं या अगली स्थिति पर जाएं!',
        'help_intro': 'नियंत्रणों को समझें:',
        'help_root': 'व्यायाम के मूल स्वर को परिभाषित करता है।',
        'help_scale': 'स्केल परिवार (पेंटाटोनिक, डायटोनिक, आदि) चुनता है।',
        'help_mode': 'चयनित परिवार के भीतर मोड या भिन्नता को बदलता है।',
        'help_ex': 'ध्वनि गति पैटर्न बदलता है (ऊपर/नीचे, छलांग, अर्पेगियो)।',
        'help_strings': 'फ़्रेटबोर्ड पर विशिष्ट स्ट्रिंग समूहों पर अभ्यास को अलग करें।',
        'help_speed': 'प्रति मिनट बीट्स को समायोजित करता है। "auto" मोड हर X दोहराव पर 10 BPM बढ़ाता है।',
        'help_challenge': 'आपकी दृश्य स्मृति को प्रशिक्षित करने के लिए मार्करों को उत्तरोत्तर छुपाता है!',
        'help_lbl_pos': 'स्थितियां 1-5',
        'help_positions': 'CAGED प्रणाली के स्वरूपों का प्रतिनिधित्व करते हैं, स्केल को याद रखने में आसान ब्लॉकों में विभाजित करते हैं।',
        'help_lbl_full': 'पूरा स्केल',
        'help_full_scale': 'उपकरण के पूरे फ़्रेटबोर्ड को प्रदर्शित करता है, जिससे एक मनोरम दृश्य मिलता है कि स्थितियां कैसे जुड़ती हैं।',
        'bt_modal_title': 'हार्मनी आइडिया',
        'bt_modal_text': 'इस स्केल पर पूरी तरह से कामचलाऊ व्यवस्था (इंप्रोवाइज़) करने के लिए निम्नलिखित कॉर्ड्स के साथ एक बैकिंग ट्रैक रिकॉर्ड करें या खोजें:',
        'bt_style': 'शैली:',
        'bt_desc_1': 'क्लासिक पॉप/रॉक प्रोग्रेसन',
        'bt_desc_2': 'डोरियन ग्रूव वैम्प',
        'bt_desc_3': 'फ्रिगियन / मेटल वैम्प',
        'bt_desc_4': 'लिडियान / ड्रीमी वैम्प',
        'bt_desc_5': 'सदर्न रॉक क्लासिक',
        'bt_desc_6': 'एपिक माइनर रॉक',
        'bt_desc_7': 'डार्क टेंशन',
        'bt_desc_8': 'टेक्सास / कंट्री ब्लूज़',
        'bt_desc_9': 'पारंपरिक माइनर ब्लूज़',
        'bt_desc_10': 'नियोक्लासिकल टेंशन / फ्लेमेंको',
        'bt_desc_11': 'माइनर जैज़ / फ्यूजन',
        'bt_desc_12': 'निरंतर तनाव (डिमिनिश्ड कॉर्ड)',
        'bt_desc_13': 'होल टोन एटमॉस्फियर (ऑगमेंटेड कॉर्ड)',
        'bt_desc_14': 'स्टैटिक वैम्प / ड्रोन',
        'lbl_backing_track': 'Backing Track',
        'lbl_harmonic_field': 'हार्मोनिक फील्ड',
        'lbl_degree': 'डिग्री',
        'hf_not_applicable': 'हार्मोनिक फील्ड लागू नहीं (गैर-डायटोनिक स्केल)।'
    },
    'ar': { 
        'str_all': '6 أوتار', 'lbl_auto': 'auto', 'starting_in': 'يبدأ في', 'roots': ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'], 'skin_light': '☀️ فاتح', 'skin_dark': '🌙 داكن', 'skin_vintage': '🎸 كلاسيكي', 'title': 'معلم السلالم', 'lbl_root': 'الجذر', 'lbl_scale': 'السلم', 'lbl_mode': 'تنوع', 'lbl_ex': 'تمرين', 'lbl_bpm': 'السرعة', 'lbl_challenge': 'تحدي', 'btn_play_full': 'عزف السلم كاملاً', 'btn_play': 'عزف', 'btn_stop': 'إيقاف', 'position': 'موضع', 'frets': 'دساتين', 'ex_1': '1. صعود وهبوط السلم', 'ex_2': '2. مرتان لكل نغمة', 'ex_3': '3. 3 مرات لكل نغمة', 'ex_4': '4. مجموعات ثلاثية (1-2-3, 2-3-4...)', 'ex_5': '5. مجموعات رباعية (1-2-3-4, 2-3-4-5...)', 'ex_6': '6. قفزات ثلثية (1-3, 2-4, 3-5...)', 'ex_7': '7. تتابعات ثلاثية', 'ex_8': '8. تتابعات رباعية', 'ex_9': '9. قفز الأوتار (6-4, 5-3, 4-2...)', 'Pentatônica': 'خماسي', 'Maior': 'كبير', 'Menor': 'صغير', 'Modos Gregos': 'مقامات', 'Jônio (Maior)': 'أيوني', 'Dórico': 'دوري', 'Frígio': 'فريجي', 'Lídio': 'ليدي', 'Mixolídio': 'ميكسوليدي', 'Eólio (Menor)': 'إيولي', 'Lócrio': 'لوكري', 'Escala Blues': 'سلم البلوز', 'Menor Harmônica': 'صغير هارموني', 'Padrão': 'قياسي', 'Menor Melódica': 'صغير لحني', 'Escalas Simétricas': 'سلالم متماثلة', 'Diminuta (Tom-Semitom)': 'متناقص', 'Dom Diminuta (Semitom-Tom)': 'متناقص سائد', 'Hexafônica (Tons Inteiros)': 'نغمة كاملة',
        'help_title': 'المساعدة والميزات',
        'help_level_notice': '⚠️ يوصى بهذا البرنامج للطلاب في المستوى المتوسط.',
        'help_how_to_start_title': 'كيف تبدأ؟',
        'help_how_to_start_text': 'اضبط آلتك على الضبط القياسي (EADGBE). انقر على زر "عزف" في الموضع الأول واتبع النغمات الوامضة على الشاشة. زد السرعة أو انتقل إلى الموضع التالي عندما تشعر بالثقة!',
        'help_intro': 'افهم عناصر التحكم:',
        'help_root': 'يحدد النغمة الأساسية للتمرين.',
        'help_scale': 'يختار عائلة السلالم (خماسي، دياتوني، إلخ).',
        'help_mode': 'يغير المقام أو التنوع داخل العائلة المحددة.',
        'help_ex': 'يغير نمط حركة الصوت (صعود/هبوط، قفزات، تتابعات).',
        'help_strings': 'اعزل التدريب على مجموعات أوتار محددة.',
        'help_speed': 'يضبط النبضات في الدقيقة. وضع "auto" يزيد 10 نبضات كل X تكرارات.',
        'help_challenge': 'يخفي العلامات تدريجياً لتدريب ذاكرتك البصرية!',
        'help_lbl_pos': 'مواضع 1-5',
        'help_positions': 'تمثل تنسيقات نظام CAGED، وتقسيم السلم إلى كتل سهلة الحفظ.',
        'help_lbl_full': 'السلم الكامل',
        'help_full_scale': 'يعرض لوحة فريتس الآلة بالكامل، مما يوفر عرضاً بانورامياً لكيفية اتصال المواضع.',
        'bt_modal_title': 'فكرة تناغم',
        'bt_modal_text': 'قم بتسجيل أو البحث عن مسار خلفي (Backing Track) يحتوي على الأوتار التالية للارتجال بشكل مثالي على هذا السلم:',
        'bt_style': 'الأسلوب:',
        'bt_desc_1': 'تقدم بوب/روك كلاسيكي',
        'bt_desc_2': 'دوريان جروف فامب',
        'bt_desc_3': 'فريجيان / ميتال فامب',
        'bt_desc_4': 'ليديان / فامب حالم',
        'bt_desc_5': 'كلاسيكيات الروك الجنوبي',
        'bt_desc_6': 'روك ثانوي ملحمي',
        'bt_desc_7': 'توتر مظلم',
        'bt_desc_8': 'تكساس / كونتري بلوز',
        'bt_desc_9': 'بلوز ثانوي تقليدي',
        'bt_desc_10': 'توتر نيوكلاسيكي / فلامنكو',
        'bt_desc_11': 'جاز ثانوي / فيوجن',
        'bt_desc_12': 'توتر مستمر (وتر متناقص)',
        'bt_desc_13': 'جو نغمة كاملة (وتر متزايد)',
        'bt_desc_14': 'فامب ثابت / درون',
        'lbl_backing_track': 'Backing Track',
        'lbl_harmonic_field': 'المجال التوافقي',
        'lbl_degree': 'درجة',
        'hf_not_applicable': 'المجال التوافقي غير قابل للتطبيق (سلم غير دياتوني).'
    },
    'bn': { 
        'str_all': '৬ তার', 'lbl_auto': 'auto', 'starting_in': 'শুরু হচ্ছে', 'roots': ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'], 'skin_light': '☀️ হালকা', 'skin_dark': '🌙 গাঢ়', 'skin_vintage': '🎸 ভিন্টেজ', 'title': 'স্কেল টিউটর', 'lbl_root': 'রুট (Root)', 'lbl_scale': 'স্কেল', 'lbl_mode': 'ভিন্নতা', 'lbl_ex': 'ব্যায়াম', 'lbl_bpm': 'গতি', 'lbl_challenge': 'চ্যালেঞ্জ', 'btn_play_full': 'সম্পূর্ণ স্কেল বাজান', 'btn_play': 'বাজান', 'btn_stop': 'থামুন', 'position': 'অবস্থান', 'frets': 'ফ্রেট', 'ex_1': '১. সম্পূর্ণ স্কেল উপরে-নিচে', 'ex_2': '২. প্রতিটি নোট ২ বার', 'ex_3': '৩. প্রতিটি নোট ৩ বার', 'ex_4': '৪. ৩ এর গ্রুপ (১-২-৩, ২-৩-৪...)', 'ex_5': '৫. ৪ এর গ্রুপ (১-২-৩-৪, ২-৩-৪-৫...)', 'ex_6': '৬. থার্ডস জাম্প (১-৩, ২-৪, ৩-৫...)', 'ex_7': '৭. ট্রায়াড আর্পেজিওস', 'ex_8': '৮. টেট্রাড আর্পেজিওস', 'ex_9': '৯. স্ট্রিং স্কিপিং (৬-৪, ৫-৩, ৪-২...)', 'Pentatônica': 'পেন্টাটোনিক', 'Maior': 'মেজর', 'Menor': 'মাইনর', 'Modos Gregos': 'মোডস', 'Jônio (Maior)': 'আয়নিয়ান', 'Dórico': 'ডোরিয়ান', 'Frígio': 'ফ্রিজিয়ান', 'Lídio': 'লিডিয়ান', 'Mixolídio': 'মিক্সোলিডিয়ান', 'Eólio (Menor)': 'এওলিয়ান', 'Lócrio': 'লোক্রিয়ান', 'Escala Blues': 'ব্লুজ স্কেল', 'Menor Harmônica': 'হারমোনিক মাইনর', 'Padrão': 'স্ট্যান্ডার্ড', 'Menor Melódica': 'মেলোডিক মাইনর', 'Escalas Simétricas': 'সিমেট্রিকাল স্কেল', 'Diminuta (Tom-Semitom)': 'ডিমিনিশড', 'Dom Diminuta (Semitom-Tom)': 'ডোম ডিমিনিশড', 'Hexafônica (Tons Inteiros)': 'হোল টোন',
        'help_title': 'সাহায্য এবং বৈশিষ্ট্য',
        'help_level_notice': '⚠️ এই সফ্টওয়্যারটি মধ্যবর্তী স্তরের শিক্ষার্থীদের জন্য সুপারিশ করা হয়।',
        'help_how_to_start_title': 'কীভাবে শুরু করবেন?',
        'help_how_to_start_text': 'আপনার বাদ্যযন্ত্রটি স্ট্যান্ডার্ড টিউনিংয়ে (EADGBE) টিউন করুন। প্রথম অবস্থানে "বাজান" বোতামে ক্লিক করুন এবং স্ক্রিনে ফ্ল্যাশিং নোটগুলি অনুসরণ করুন। আপনি যখন আত্মবিশ্বাসী বোধ করবেন তখন গতি বাড়ান বা পরবর্তী অবস্থানে যান!',
        'help_intro': 'নিয়ন্ত্রণগুলি বুঝুন:',
        'help_root': 'অনুশীলনের মূল নোট সংজ্ঞায়িত করে।',
        'help_scale': 'স্কেল পরিবার বেছে নেয় (পেন্টাটোনিক, ডায়াটোনিক ইত্যাদি)।',
        'help_mode': 'নির্বাচিত পরিবারের মধ্যে মোড বা বৈচিত্র্য পরিবর্তন করে।',
        'help_ex': 'শব্দ চলাচলের প্যাটার্ন পরিবর্তন করে (উপরে/নীচে, লাফ, আর্পেজিওস)।',
        'help_strings': 'ফ্রেটবোর্ডে নির্দিষ্ট স্ট্রিং গ্রুপে অনুশীলন বিচ্ছিন্ন করুন।',
        'help_speed': 'প্রতি মিনিটে বিটগুলি সামঞ্জস্য করে। "auto" মোড প্রতি X পুনরাবৃত্তিতে 10 BPM বাড়ায়।',
        'help_challenge': 'আপনার ভিজ্যুয়াল মেমরিকে প্রশিক্ষণ দিতে ধীরে ধীরে মার্কারগুলি লুকিয়ে রাখে!',
        'help_lbl_pos': 'অবস্থান 1-5',
        'help_positions': 'CAGED সিস্টেমের ফর্ম্যাটগুলি উপস্থাপন করে, স্কেলটিকে সহজে মনে রাখা যায় এমন ব্লকগুলিতে বিভক্ত করে।',
        'help_lbl_full': 'সম্পূর্ণ স্কেল',
        'help_full_scale': 'যন্ত্রের সম্পূর্ণ ফ্রেটবোর্ড প্রদর্শন করে, অবস্থানগুলি কীভাবে সংযুক্ত হয় তার একটি প্যানোরামিক দৃশ্য প্রদান করে।',
        'bt_modal_title': 'হারমোনি আইডিয়া',
        'bt_modal_text': 'এই স্কেলে নিখুঁতভাবে ইম্প্রোভাইজ করতে নিম্নলিখিত কর্ডগুলির সাথে একটি ব্যাকিং ট্র্যাক রেকর্ড বা অনুসন্ধান করুন:',
        'bt_style': 'স্টাইল:',
        'bt_desc_1': 'ক্লাসিক পপ/রক প্রোগ্রেশন',
        'bt_desc_2': 'ডোরিয়ান গ্রুভ ভ্যাম্প',
        'bt_desc_3': 'ফ্রিজিয়ান / মেটাল ভ্যাম্প',
        'bt_desc_4': 'লিডিয়ান / ড্রিমি ভ্যাম্প',
        'bt_desc_5': 'সাউদার্ন রক ক্লাসিক',
        'bt_desc_6': 'এপিক মাইনর রক',
        'bt_desc_7': 'ডার্ক টেনশন',
        'bt_desc_8': 'টেক্সাস / কান্ট্রি ব্লুজ',
        'bt_desc_9': 'ট্র্যাডিশনাল মাইনর ব্লুজ',
        'bt_desc_10': 'নিওক্লাসিক্যাল টেনশন / ফ্ল্যামেনকো',
        'bt_desc_11': 'মাইনর জ্যাজ / ফিউশন',
        'bt_desc_12': 'কন্টিনিউয়াস টেনশন (ডিমিনিশড কর্ড)',
        'bt_desc_13': 'হোল টোন অ্যাটমোস্ফিয়ার (অগমেন্টেড কর্ড)',
        'bt_desc_14': 'স্ট্যাটিক ভ্যাম্প / ড্রোন',
        'lbl_backing_track': 'Backing Track',
        'lbl_harmonic_field': 'হারমোনিক ফিল্ড',
        'lbl_degree': 'ডিগ্রি',
        'hf_not_applicable': 'হারমোনিক ফিল্ড প্রযোজ্য নয় (নন-ডায়াটোনিক স্কেল)।'
    },
    'ur': { 
        'str_all': '6 تار', 'lbl_auto': 'auto', 'starting_in': 'شروع ہو رہا ہے', 'roots': ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'], 'skin_light': '☀️ ہلکا', 'skin_dark': '🌙 گہرا', 'skin_vintage': '🎸 ونٹیج', 'title': 'سکیل ٹیوٹر', 'lbl_root': 'روٹ', 'lbl_scale': 'سکیل', 'lbl_mode': 'تغیر', 'lbl_ex': 'مشق', 'lbl_bpm': 'رفتار', 'lbl_challenge': 'چیلنج', 'btn_play_full': 'پورا سکیل بجائیں', 'btn_play': 'بجائیں', 'btn_stop': 'روکیں', 'position': 'پوزیشن', 'frets': 'فریٹس', 'ex_1': '1. پورا سکیل اوپر نیچے', 'ex_2': '2. 2 بار ہر نوٹ', 'ex_3': '3. 3 بار ہر نوٹ', 'ex_4': '4. 3 کے گروپس (1-2-3, 2-3-4...)', 'ex_5': '5. 4 کے گروپس (1-2-3-4, 2-3-4-5...)', 'ex_6': '6. تھرڈز جمپ (1-3, 2-4, 3-5...)', 'ex_7': '7. ٹرائڈ آرپیجیوس', 'ex_8': '8. ٹیٹراڈ آرپیجیوس', 'ex_9': '9. سٹرنگ سکپنگ (6-4, 5-3, 4-2...)', 'Pentatônica': 'پینٹاٹونک', 'Maior': 'میجر', 'Menor': 'مائنر', 'Modos Gregos': 'موڈز', 'Jônio (Maior)': 'آیونین', 'Dórico': 'ڈورین', 'Frígio': 'فریجین', 'Lídio': 'لیڈین', 'Mixolídio': 'مکسولیڈین', 'Eólio (Menor)': 'ایولین', 'Lócrio': 'لوکرین', 'Escala Blues': 'بلوز سکیل', 'Menor Harmônica': 'ہارمونک مائنر', 'Padrão': 'سٹینڈرڈ', 'Menor Melódica': 'میلوڈک مائنر', 'Escalas Simétricas': 'سمیٹریکل سکیل', 'Diminuta (Tom-Semitom)': 'ڈیمینشڈ', 'Dom Diminuta (Semitom-Tom)': 'ڈوم ڈیمینشڈ', 'Hexafônica (Tons Inteiros)': 'ہول ٹون',
        'help_title': 'مدد اور خصوصیات',
        'help_level_notice': '⚠️ یہ سافٹ ویئر انٹرمیڈیٹ سطح کے طلباء کے لیے تجویز کیا جاتا ہے۔',
        'help_how_to_start_title': 'کیسے شروع کریں؟',
        'help_how_to_start_text': 'اپنے آلے کو معیاری ٹیوننگ (EADGBE) پر ٹیون کریں۔ پہلی پوزیشن پر "بجائیں" بٹن پر کلک کریں اور اسکرین پر چمکتے ہوئے نوٹس پر عمل کریں۔ جب آپ پر اعتماد محسوس کریں تو رفتار بڑھائیں یا اگلی پوزیشن پر جائیں!',
        'help_intro': 'کنٹرولز کو سمجھیں:',
        'help_root': 'مشق کے بنیادی نوٹ کی وضاحت کرتا ہے۔',
        'help_scale': 'سکیل فیملی (پینٹاٹونک، ڈائیٹونک وغیرہ) کا انتخاب کرتا ہے۔',
        'help_mode': 'منتخب فیملی کے اندر موڈ یا تغیر کو تبدیل کرتا ہے۔',
        'help_ex': 'آواز کی نقل و حرکت کے پیٹرن کو تبدیل کرتا ہے (اوپر/نیچے، چھلانگ، آرپیجیوس)۔',
        'help_strings': 'فریٹ بورڈ پر مخصوص سٹرنگ گروپس پر مشق کو الگ کریں۔',
        'help_speed': 'فی منٹ بیٹس کو ایڈجسٹ کرتا ہے۔ "auto" موڈ ہر X تکرار پر 10 BPM بڑھاتا ہے۔',
        'help_challenge': 'آپ کی بصری یادداشت کو تربیت دینے کے لیے مارکرز کو بتدریج چھپاتا ہے!',
        'help_lbl_pos': 'پوزیشنز 1-5',
        'help_positions': 'CAGED سسٹم کے فارمیٹس کی نمائندگی کرتے ہیں، سکیل کو یاد رکھنے میں آسان بلاکس میں تقسیم کرتے ہیں۔',
        'help_lbl_full': 'پورا سکیل',
        'help_full_scale': 'آلے کے پورے فریٹ بورڈ کو دکھاتا ہے، جس سے پوزیشنز کے جڑنے کا پینورامک منظر ملتا ہے۔',
        'bt_modal_title': 'ہم آہنگی کا خیال',
        'bt_modal_text': 'اس سکیل پر کامل طریقے سے امپرووائز کرنے کے لیے درج ذیل کورڈز کے ساتھ بیکنگ ٹریک ریکارڈ کریں یا تلاش کریں:',
        'bt_style': 'انداز:',
        'bt_desc_1': 'کلاسک پاپ/راک پروگریشن',
        'bt_desc_2': 'ڈورین گروو ویمپ',
        'bt_desc_3': 'فریجین / میٹل ویمپ',
        'bt_desc_4': 'لیڈین / خوابیدہ ویمپ',
        'bt_desc_5': 'سدرن راک کلاسک',
        'bt_desc_6': 'ایپک مائنر راک',
        'bt_desc_7': 'تاریک تناؤ',
        'bt_desc_8': 'ٹیکساس / کنٹری بلوز',
        'bt_desc_9': 'روایتی مائنر بلوز',
        'bt_desc_10': 'نیو کلاسک تناؤ / فلیمینکو',
        'bt_desc_11': 'مائنر جاز / فیوژن',
        'bt_desc_12': 'مسلسل تناؤ (ڈیمینشڈ کورڈ)',
        'bt_desc_13': 'ہول ٹون ماحول (آگمینٹڈ کورڈ)',
        'bt_desc_14': 'جامد ویمپ / ڈرون',
        'lbl_backing_track': 'Backing Track',
        'lbl_harmonic_field': 'ہارمونک فیلڈ',
        'lbl_degree': 'ڈگری',
        'hf_not_applicable': 'ہارمونک فیلڈ لاگو نہیں (غیر ڈائیٹونک سکیل)۔'
    }
};

// Constantes de Teoria Musical
const notasCromaticas = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];
const afinacaoIndices = [4, 11, 7, 2, 9, 4];
const openStringFreqs = [329.63, 246.94, 196.00, 146.83, 110.00, 82.41];

// Banco de Escalas e Modelos
const bancoDeEscalas = {
    'Pentatônica': { 'Maior': { i: [0, 2, 4, 7, 9], c: 0 }, 'Menor': { i: [0, 3, 5, 7, 10], c: 3 } },
    'Escala Blues': { 'Maior': { i: [0, 2, 3, 4, 7, 9], c: 0 }, 'Menor': { i: [0, 3, 5, 6, 7, 10], c: 3 } },
    'Modos Gregos': { 'Jônio (Maior)': { i: [0, 2, 4, 5, 7, 9, 11], c: 0 }, 'Dórico': { i: [0, 2, 3, 5, 7, 9, 10], c: -2 }, 'Frígio': { i: [0, 1, 3, 5, 7, 8, 10], c: -4 }, 'Lídio': { i: [0, 2, 4, 6, 7, 9, 11], c: -5 }, 'Mixolídio': { i: [0, 2, 4, 5, 7, 9, 10], c: -7 }, 'Eólio (Menor)': { i: [0, 2, 3, 5, 7, 8, 10], c: 3 }, 'Lócrio': { i: [0, 1, 3, 5, 6, 8, 10], c: 1 } },
    'Menor Harmônica': { 'Padrão': { i: [0, 2, 3, 5, 7, 8, 11], c: 3 } },
    'Menor Melódica': { 'Padrão': { i: [0, 2, 3, 5, 7, 9, 11], c: 3 } },
    'Escalas Simétricas': { 'Diminuta (Tom-Semitom)': { i: [0, 2, 3, 5, 6, 8, 9, 11], c: 0 }, 'Dom Diminuta (Semitom-Tom)': { i: [0, 1, 3, 4, 6, 7, 9, 10], c: 0 }, 'Hexafônica (Tons Inteiros)': { i: [0, 2, 4, 6, 8, 10], c: 0 } }
};